name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - 
      name: Build the Docker image
      run: docker build -t ga63qes/prices -f Dockerfile .
    -
      name: Generate Deployment Package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.MY_AWS_SECRET_KEY }}
        application_name: New_York_Prices
        environment_name: Newyorkprices-env
        version_label: "version-7"
        region: us-west-1
        deployment_package: deploy.zip
